name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: notifications-workers
    secrets: inherit

  notifications-inbox-deployment:
    needs: [cd]
    name: "Deploy core to: dev"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment (notifications-inbox)
        id: deploy
        uses: decentraland/dcl-deploy-action@main
        with:
          dockerImage: "quay.io/decentraland/notifications-workers:next"
          serviceName: notifications-inbox
          env: dev
          token: ${{ secrets.GITHUB_TOKEN }}
