name: CI/CD on PR

on:
  pull_request:

jobs:
  pr:
    uses: decentraland/platform-actions/.github/workflows/apps-pr.yml@updates
    with:
      service-name: notifications-workers
    secrets: inherit
